CREATE TABLE ROLE (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL
);

CREATE TABLE SCHOOL (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    is_active BIT NOT NULL DEFAULT 1
);

CREATE TABLE USER_APP (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    is_active BIT NOT NULL DEFAULT 1,
    school_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT FK_USER_SCHOOL FOREIGN KEY (school_id) REFERENCES SCHOOL(id),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (role_id) REFERENCES ROLE(id)
);

CREATE TABLE PERSON_TYPE (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE PERSON (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    is_active BIT NOT NULL DEFAULT 1,
    person_type_id BIGINT NOT NULL,
    CONSTRAINT FK_PERSON_TYPE FOREIGN KEY (person_type_id) REFERENCES PERSON_TYPE(id)
);

CREATE TABLE SCHOOL_PERSON (
    school_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    PRIMARY KEY (school_id, teacher_id),
    CONSTRAINT FK_SCHOOL_PERSON_SCHOOL FOREIGN KEY (school_id) REFERENCES SCHOOL(id),
    CONSTRAINT FK_SCHOOL_PERSON_PERSON FOREIGN KEY (teacher_id) REFERENCES PERSON(id)
);

CREATE TABLE STUDENT_GUARDIAN (
    student_id BIGINT NOT NULL,
    guardian_id BIGINT NOT NULL,
    PRIMARY KEY (student_id, guardian_id),
    CONSTRAINT FK_STUDENT_GUARDIAN_STUDENT FOREIGN KEY (student_id) REFERENCES PERSON(id),
    CONSTRAINT FK_STUDENT_GUARDIAN_GUARDIAN FOREIGN KEY (guardian_id) REFERENCES PERSON(id)
);

CREATE TABLE COURSE (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    level VARCHAR(255) NOT NULL,
    letter VARCHAR(255) NOT NULL,
    school_id BIGINT NOT NULL,
    homeroom_teacher_id BIGINT NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_COURSE_SCHOOL FOREIGN KEY (school_id) REFERENCES SCHOOL(id),
    CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY (homeroom_teacher_id) REFERENCES PERSON(id)
);

CREATE TABLE SCHOOL_SUPPLY (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(MAX) NOT NULL,
    is_active BIT NOT NULL DEFAULT 1
);

CREATE TABLE COURSE_SUPPLY_LIST (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    school_supply_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    is_active BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_SUPPLYLIST_SUPPLY FOREIGN KEY (school_supply_id) REFERENCES SCHOOL_SUPPLY(id),
    CONSTRAINT FK_SUPPLYLIST_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(id)
);

CREATE TABLE STUDENT_COURSE (
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    PRIMARY KEY (student_id, course_id),
    CONSTRAINT FK_STUDENTCOURSE_STUDENT FOREIGN KEY (student_id) REFERENCES PERSON(id),
    CONSTRAINT FK_STUDENTCOURSE_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(id)
);


------------------------------------------------------------------------------
